// <auto-generated />
using System;
using DarRuqayah_QuranApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DarRuqayah_QuranApp.Migrations
{
    [DbContext(typeof(QuranAppContext))]
    partial class QuranAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassTime");

                    b.Property<string>("Image");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OstadId");

                    b.Property<int>("UserId");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("OstadId");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.DailyTask", b =>
                {
                    b.Property<int>("DailyTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("DailyHefzValue");

                    b.Property<DateTime>("Date");

                    b.Property<byte>("GoodBehavier");

                    b.Property<byte>("Hearing");

                    b.Property<byte>("Hefz");

                    b.Property<byte>("NewReapet");

                    b.Property<byte>("OldReapet");

                    b.Property<int?>("OstadId");

                    b.Property<int?>("UserId");

                    b.HasKey("DailyTaskId");

                    b.HasIndex("OstadId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.MonthTask", b =>
                {
                    b.Property<int>("MonthTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("FinalDailyGrade");

                    b.Property<byte>("FinalGrade");

                    b.Property<byte>("FinalWeeklyGrade");

                    b.HasKey("MonthTaskId");

                    b.ToTable("MonthTasks");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.Ostad", b =>
                {
                    b.Property<int>("OstadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("CV");

                    b.Property<string>("Country");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Tell")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.HasKey("OstadId");

                    b.ToTable("Ostads");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<int?>("ClassRoomId");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<int>("HefzValue");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ParentTell")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Tell")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.HasKey("UserId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.WeeklyTask", b =>
                {
                    b.Property<int>("WeeklyTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Ada");

                    b.Property<DateTime>("Date");

                    b.Property<byte>("GoodHefz");

                    b.Property<int?>("MonthTaskId");

                    b.Property<byte>("Tajvid");

                    b.Property<int?>("UserId");

                    b.HasKey("WeeklyTaskId");

                    b.HasIndex("MonthTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklyTasks");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.ClassRoom", b =>
                {
                    b.HasOne("DarRuqayah_QuranApp.Models.Ostad", "Ostad")
                        .WithMany()
                        .HasForeignKey("OstadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.DailyTask", b =>
                {
                    b.HasOne("DarRuqayah_QuranApp.Models.Ostad", "Ostad")
                        .WithMany()
                        .HasForeignKey("OstadId");

                    b.HasOne("DarRuqayah_QuranApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.User", b =>
                {
                    b.HasOne("DarRuqayah_QuranApp.Models.ClassRoom")
                        .WithMany("Users")
                        .HasForeignKey("ClassRoomId");
                });

            modelBuilder.Entity("DarRuqayah_QuranApp.Models.WeeklyTask", b =>
                {
                    b.HasOne("DarRuqayah_QuranApp.Models.MonthTask", "MonthTask")
                        .WithMany()
                        .HasForeignKey("MonthTaskId");

                    b.HasOne("DarRuqayah_QuranApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
